version: "3.8"

services:
  ubuntu:
    container_name: "${APP_NAME}_ubuntu"
    ports:
      - 8081:${APP_HTTP_PORT}
      - 8082:${APP_HTTPS_PORT}
    build:
      context: ./
      dockerfile: docker-compose/ubuntu/ubuntu.dockerfile
      args:
        USER: ${APP_USER}
        UID: ${APP_UID}
    tty: true

  debian:
    container_name: "${APP_NAME}_devian"
    ports:
      - 9091:${APP_HTTP_PORT}
      - 9092:${APP_HTTPS_PORT}
    build:
      context: ./
      dockerfile: docker-compose/debian/debian.dockerfile
      args:
        USER: ${APP_USER}
        UID: ${APP_UID}
    tty: true

  centos:
    container_name: "${APP_NAME}_centos"
    ports:
      - 9091:${APP_HTTP_PORT}
      - 9092:${APP_HTTPS_PORT}
    build:
      context: ./
      dockerfile: docker-compose/centos/centos.dockerfile
      args:
        USER: ${APP_USER}
        UID: ${APP_UID}
    tty: true